[package]
name = "sbdf"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
insta = { version = "1.41", features = ["ron"] }
